-- DDL extracted from 113_cms_news_media.sql (sha256 8f25ed7e70a524d0e3fa55a6d3fa742f7674bd578759b83dc460965fac8a9823)
CREATE TABLE IF NOT EXISTS cms_posts (
    id                   CHAR(36)      NOT NULL,
    tenant_id            CHAR(36)      NOT NULL DEFAULT '00000000-0000-4000-a000-000000000001',
    category             VARCHAR(50)   NOT NULL DEFAULT 'news' COMMENT 'news | announcement | activity | press_release',
    title_th             VARCHAR(300)  NOT NULL,
    title_en             VARCHAR(300)  NOT NULL,
    title_zh             VARCHAR(300)  NOT NULL,
    slug                 VARCHAR(350)  NOT NULL,
    excerpt_th           TEXT          NULL,
    excerpt_en           TEXT          NULL,
    excerpt_zh           TEXT          NULL,
    content_th           LONGTEXT      NULL,
    content_en           LONGTEXT      NULL,
    content_zh           LONGTEXT      NULL,
    cover_image_url      VARCHAR(500)  NULL,
    author_name          VARCHAR(150)  NOT NULL DEFAULT 'UTKIC Public Relations',
    views_count          INT           NOT NULL DEFAULT 0,
    is_featured          TINYINT(1)    NOT NULL DEFAULT 0,
    is_pinned            TINYINT(1)    NOT NULL DEFAULT 0,
    status               VARCHAR(20)   NOT NULL DEFAULT 'published' COMMENT 'draft | published | archived',
    published_at         DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_cms_status_date (tenant_id, status, published_at),
    KEY idx_cms_category (category)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cms_banners (
    id                   CHAR(36)      NOT NULL,
    tenant_id            CHAR(36)      NOT NULL DEFAULT '00000000-0000-4000-a000-000000000001',
    title_th             VARCHAR(255)  NOT NULL,
    title_en             VARCHAR(255)  NOT NULL,
    title_zh             VARCHAR(255)  NOT NULL,
    subtitle_th          VARCHAR(500)  NULL,
    subtitle_en          VARCHAR(500)  NULL,
    subtitle_zh          VARCHAR(500)  NULL,
    button_text_th       VARCHAR(100)  NULL,
    button_text_en       VARCHAR(100)  NULL,
    button_text_zh       VARCHAR(100)  NULL,
    button_url           VARCHAR(500)  NULL,
    image_url            VARCHAR(500)  NOT NULL,
    display_order        INT           NOT NULL DEFAULT 0,
    is_active            TINYINT(1)    NOT NULL DEFAULT 1,
    created_at           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS cms_faculty_directory (
    id                   CHAR(36)      NOT NULL,
    tenant_id            CHAR(36)      NOT NULL DEFAULT '00000000-0000-4000-a000-000000000001',
    name_th              VARCHAR(150)  NOT NULL,
    name_en              VARCHAR(150)  NOT NULL,
    name_zh              VARCHAR(150)  NOT NULL,
    academic_title_th    VARCHAR(100)  NULL,
    academic_title_en    VARCHAR(100)  NULL,
    academic_title_zh    VARCHAR(100)  NULL,
    position_th          VARCHAR(150)  NULL,
    position_en          VARCHAR(150)  NULL,
    position_zh          VARCHAR(150)  NULL,
    department           VARCHAR(150)  NOT NULL DEFAULT 'International College',
    email                VARCHAR(150)  NULL,
    phone                VARCHAR(50)   NULL,
    office_room          VARCHAR(100)  NULL,
    avatar_url           VARCHAR(500)  NULL,
    bio_th               TEXT          NULL,
    bio_en               TEXT          NULL,
    bio_zh               TEXT          NULL,
    research_interests   TEXT          NULL,
    display_order        INT           NOT NULL DEFAULT 0,
    is_active            TINYINT(1)    NOT NULL DEFAULT 1,
    created_at           DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
