-- DDL extracted from 118_admission_intake_pipeline.sql (sha256 9c2b9d8258d26d52f3da87b5869450335afe70473488576861f3c1034ab41d37)
CREATE TABLE IF NOT EXISTS ic_admission_programs (
    id                  CHAR(36)       NOT NULL,
    tenant_id           CHAR(36)       NOT NULL DEFAULT '00000000-0000-4000-a000-000000000001',
    program_code        VARCHAR(50)    NOT NULL,
    name_th             VARCHAR(255)   NOT NULL,
    name_en             VARCHAR(255)   NOT NULL,
    degree_level        ENUM('bachelor','master','doctorate','certificate') NOT NULL DEFAULT 'bachelor',
    faculty_code        VARCHAR(20)    NOT NULL DEFAULT 'IC',
    tuition_fee_thb     DECIMAL(12,2)  NOT NULL DEFAULT 0.00,
    application_fee_thb DECIMAL(10,2)  NOT NULL DEFAULT 1000.00,
    quota               INT            NOT NULL DEFAULT 30,
    academic_year       INT            NOT NULL DEFAULT 2569,
    semester            INT            NOT NULL DEFAULT 1,
    requirements_json   TEXT           NULL,
    is_active           TINYINT(1)     NOT NULL DEFAULT 1,
    created_at          DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_adm_program (tenant_id, program_code, academic_year, semester)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ic_admission_applications (
    id                       CHAR(36)       NOT NULL,
    tenant_id                CHAR(36)       NOT NULL DEFAULT '00000000-0000-4000-a000-000000000001',
    tracking_code            VARCHAR(25)    NOT NULL COMMENT 'User-facing tracking reference e.g. ADM-2569-123456',
    program_id               CHAR(36)       NOT NULL COMMENT 'FK ic_admission_programs.id',
    applicant_type           ENUM('th','intl') NOT NULL DEFAULT 'intl',
    title                    VARCHAR(30)    NULL,
    name_th                  VARCHAR(190)   NULL,
    name_en                  VARCHAR(190)   NOT NULL,
    nationality_code         CHAR(2)        NOT NULL DEFAULT 'CN' COMMENT 'FK ref_country.code',
    date_of_birth            VARCHAR(255)   NULL COMMENT 'L4 encrypted with appEncryptPII()',
    date_of_birth_bidx       CHAR(64)       NULL COMMENT 'HMAC-SHA256 blind index for search/dedup',
    id_card_or_passport_no   VARCHAR(255)   NOT NULL COMMENT 'L4 encrypted with appEncryptPII()',
    id_card_or_passport_bidx CHAR(64)      NOT NULL COMMENT 'HMAC-SHA256 blind index for search/dedup',
    mrz_line1                VARCHAR(100)   NULL,
    mrz_line2                VARCHAR(100)   NULL,
    mrz_valid                TINYINT(1)     NOT NULL DEFAULT 0,
    email                    VARCHAR(190)   NOT NULL,
    phone                    VARCHAR(50)    NOT NULL,
    wechat_or_line_id        VARCHAR(100)   NULL,
    emergency_contact        VARCHAR(255)   NULL,
    previous_degree          VARCHAR(190)   NULL,
    previous_school          VARCHAR(255)   NULL,
    previous_gpa             DECIMAL(3,2)   NULL,
    language_test_type       VARCHAR(50)    NULL COMMENT 'IELTS, TOEFL, Duolingo, HSK, Placement',
    language_score           VARCHAR(50)    NULL,
    status                   ENUM('submitted','under_review','interview_scheduled','approved','rejected','payment_pending','enrolled') NOT NULL DEFAULT 'submitted',
    rejection_reason         TEXT           NULL,
    interview_datetime       DATETIME       NULL,
    interview_link           VARCHAR(255)   NULL,
    loa_token                CHAR(64)       NULL COMMENT 'Cryptographic verification token for digital LOA QR',
    loa_issued_at            DATETIME       NULL,
    loa_issued_by            CHAR(36)       NULL COMMENT 'FK users.id',
    created_at               DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_adm_tracking (tracking_code),
    UNIQUE KEY uq_adm_loa_token (loa_token),
    KEY idx_adm_program (program_id),
    KEY idx_adm_status (tenant_id, status),
    KEY idx_adm_passport_bidx (tenant_id, id_card_or_passport_bidx),
    KEY idx_adm_nationality (nationality_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ic_admission_payments (
    id                 CHAR(36)       NOT NULL,
    tenant_id          CHAR(36)       NOT NULL DEFAULT '00000000-0000-4000-a000-000000000001',
    application_id     CHAR(36)       NOT NULL COMMENT 'FK ic_admission_applications.id',
    payment_type       ENUM('application_fee','tuition_fee') NOT NULL DEFAULT 'application_fee',
    amount             DECIMAL(12,2)  NOT NULL,
    currency           VARCHAR(10)    NOT NULL DEFAULT 'THB',
    payment_method     ENUM('promptpay','bank_transfer','swift','credit_card') NOT NULL DEFAULT 'bank_transfer',
    slip_evidence_id   CHAR(36)       NULL COMMENT 'FK ic_evidence_document.id',
    transaction_ref    VARCHAR(100)   NULL,
    receipt_no         VARCHAR(50)    NULL COMMENT 'Official University e-Receipt number',
    status             ENUM('pending','verified','rejected') NOT NULL DEFAULT 'pending',
    verified_by        CHAR(36)       NULL COMMENT 'FK users.id (financial officer)',
    verified_at        DATETIME       NULL,
    notes              TEXT           NULL,
    created_at         DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_pay_app (application_id),
    KEY idx_pay_status (tenant_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ic_admission_reviews (
    id                 CHAR(36)       NOT NULL,
    tenant_id          CHAR(36)       NOT NULL DEFAULT '00000000-0000-4000-a000-000000000001',
    application_id     CHAR(36)       NOT NULL COMMENT 'FK ic_admission_applications.id',
    reviewer_id        CHAR(36)       NOT NULL COMMENT 'FK users.id (academic reviewer/dean)',
    stage              ENUM('doc_screening','interview','dean_approval') NOT NULL DEFAULT 'doc_screening',
    academic_score     DECIMAL(5,2)   NULL,
    language_score     DECIMAL(5,2)   NULL,
    interview_score    DECIMAL(5,2)   NULL,
    total_score        DECIMAL(5,2)   NULL,
    decision           ENUM('recommend_accept','recommend_reject','request_revision') NOT NULL,
    comments           TEXT           NULL,
    created_at         DATETIME       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_rev_app (application_id),
    KEY idx_rev_user (reviewer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
